"""Add timestamp to Vote model and update relationships

Revision ID: 037bf9fba744
Revises: 
Create Date: 2024-10-13 08:09:05.542209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037bf9fba744'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
