"""Add vote and comment indices

Revision ID: 48f4a7b30dae
Revises: 6846cbd74bd3
Create Date: 2024-10-25 08:52:45.060612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f4a7b30dae'
down_revision = '6846cbd74bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_user_scores', ['user_id', 'likes', 'dislikes'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('idx_votes_user_comment', ['user_id', 'comment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index('idx_votes_user_comment')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index('idx_comments_user_scores')

    # ### end Alembic commands ###
