"""Increase course_name length to 256 and change fields to Text

Revision ID: 704bc81d7a15
Revises: 44cf3749272a
Create Date: 2024-10-15 15:40:03.382384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704bc81d7a15'
down_revision = '44cf3749272a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
