"""add search vectors

Revision ID: 791068f5fd7c
Revises: 
Create Date: 2024-10-28 06:39:23.869948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '791068f5fd7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('idx_course_name', ['course_name'], unique=False)
        batch_op.create_index('idx_course_search', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_course_university', ['university_name'], unique=False)

    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
        batch_op.create_index('idx_university_name', ['university_name'], unique=False)
        batch_op.create_index('idx_university_program_type', ['program_type'], unique=False)
        batch_op.create_index('idx_university_search', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_university_state', ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university', schema=None) as batch_op:
        batch_op.drop_index('idx_university_state')
        batch_op.drop_index('idx_university_search', postgresql_using='gin')
        batch_op.drop_index('idx_university_program_type')
        batch_op.drop_index('idx_university_name')
        batch_op.drop_column('search_vector')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index('idx_course_university')
        batch_op.drop_index('idx_course_search', postgresql_using='gin')
        batch_op.drop_index('idx_course_name')
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###
