"""Change abbrv to Text in Course model

Revision ID: 8853b7c0c370
Revises: f8233e8b26f9
Create Date: 2024-10-17 04:57:36.023871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8853b7c0c370'
down_revision = 'f8233e8b26f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('abbrv',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('abbrv',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)

    # ### end Alembic commands ###
