"""add course materialized view

Revision ID: [autogenerated]
Revises: [previous_revision]
Create Date: [timestamp]
"""
from alembic import op

def upgrade():
    # Create materialized view for courses with their universities
    op.execute("""
        CREATE MATERIALIZED VIEW course_university_view AS
        SELECT DISTINCT
            c.id as course_id,
            c.course_name,
            c.code,
            u.program_type,
            u.university_name,
            u.id as university_id
        FROM course c
        JOIN course_requirement cr ON c.id = cr.course_id
        JOIN university u ON u.id = cr.university_id
        ORDER BY c.course_name;
        
        CREATE UNIQUE INDEX idx_course_university_view 
        ON course_university_view (course_id, university_id);
    """)

def downgrade():
    op.execute("DROP MATERIALIZED VIEW IF EXISTS course_university_view;") 