"""add course search indexes

Revision ID: [autogenerated]
Revises: [previous_revision]
Create Date: [timestamp]
"""
from alembic import op

def upgrade():
    # Create composite index for course requirements
    op.create_index(
        'idx_course_req_composite',
        'course_requirement',
        ['course_id', 'university_id'],
        unique=False
    )
    
    # Create index for university program_type for IN clause queries
    op.create_index(
        'idx_university_program_type_hash',
        'university',
        ['program_type'],
        postgresql_using='hash'
    )

def downgrade():
    op.drop_index('idx_course_req_composite')
    op.drop_index('idx_university_program_type_hash') 