"""Increase course_name length to 256 and abbrv to 50, change other fields to Text

Revision ID: f8233e8b26f9
Revises: 704bc81d7a15
Create Date: 2024-10-17 04:45:17.762664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8233e8b26f9'
down_revision = '704bc81d7a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('abbrv',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=70),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('abbrv',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
